### ISSUE TITLE
Beatmap writing problem

### ISSUE THREAD

**Issue by Sh0keR0** [ExCellRaD/osuElements#5]
beatmap.WriteFile() result in a beatmap that is missing a lot of circles, timing points and sounds.
Simply changing a beatmap AR and changing it's fileName will even cause this issue.

**Comment by ExCellRaD** [comment]
have you checked whether or not those objects are read properly? are they in the correct objects in memory? The file writing shouldn't give problems here since it just writes everything from the properties.

**Comment by Sh0keR0** [comment]
I tried different things, DbBeatmap and Beatmap produce the same result.
And yes, it's probably it is a matter of reading. Do you have the same problem or it is just me?

**Comment by ExCellRaD** [comment]
alright, try this:
make a BasicLogger object, use the beatmap.ReadFile(basiclogger) method and put a breakpoint to check the errors  in the logger.

**Comment by Sh0keR0** [comment]
29 Errors appear
http://puu.sh/nQf0g/4abe6ff7da.png

**Comment by Sh0keR0** [comment]
It seems like not all beatmaps show errors
Edit:
The numbers of errors are different from each beatmap but most of them don't show any errors
And those who do shows the same error

**Comment by Sh0keR0** [comment]
Another issue, when I use ReadFile multiple times all the objects copy themselves again (All the circles, silders, etc) which create an unplayable map.
I'll keep testing some stuff, I will tell you if I manage to solve the problem. thanks for the help

**Comment by ExCellRaD** [comment]
whoops, seems like it was always expecting the Looptype to be defined at the end of the line of an animation. fixing it atm. Did you get different errors too?

**Comment by Sh0keR0** [comment]
Nope, only the index out of bounds

**Comment by ExCellRaD** [comment]
Last merge fixed the issue, btw do you have discord? I made a server https://discord.gg/0u5HoATHFvW9VOl1 for easier communication.

**Comment by ExCellRaD** [comment]
1.0.3 fixes this issue [download](https://osu.ppy.sh/forum/t/430701)
