### ISSUE TITLE
DifficultySliderMultiplier is always 1.4 after reading a beatmap

### ISSUE THREAD

**Issue by flesnuk** [ExCellRaD/osuElements#6]
Seems like the DifficultySliderMultiplier will be always the default one instead of reading the proper DifficultySliderMultiplier from the .osu beatmap file.

Right after I create the object Beatmap from a file, if I check the propery DifficultySliderMultiplier, it will say 1.4.

**Comment by ExCellRaD** [comment]
The reader was looking for DifficultySliderMultiplier, same with SliderTickRate. Both are fixed now. I'll update the dll for you.

**Comment by ExCellRaD** [comment]
[Here you go :)](https://mega.nz/#!aAoDETBZ!wfTbK2sFSndQdNDYOfYiEyfMtxRqEtI0-QnBy6acgJA)

**Comment by flesnuk** [comment]
Thanks, now it works flawlessly :+1:
