### ISSUE TITLE
Multiplayer uses wrong GET parameter

### ISSUE THREAD

**Issue by holly-hacker** [ExCellRaD/osuElements#7]
The GET request for getting multiplayer match info (/api/get_match) uses the wrong parameter name for the match id. osuElements uses "id", while it should be "mp" , according to the [osu!api wiki](https://github.com/ppy/osu-api/wiki#parameters-5) and my testing.

Code found in:
osuElements/Api/Repositories/ApiMultiplayerRepository.cs

**Comment by ExCellRaD** [comment]
Hey thanks for letting me know, should be fixed now.
